SELECT DATE_FORMAT(SALES_DATE,'%Y') AS YEAR,DATE_FORMAT(SALES_DATE,'%m') AS MONTH, COUNT(DISTINCT(S.USER_ID)) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT(S.USER_ID))/(SELECT COUNT(USER_ID)
                         FROM USER_INFO 
                        WHERE YEAR(JOINED)='2021'),1) AS PUCHASED_RATIO
  FROM ONLINE_SALE S
  JOIN USER_INFO U
 WHERE S.USER_ID=U.USER_ID
   AND YEAR(U.JOINED)='2021'
 GROUP BY DATE_FORMAT(SALES_DATE,'%Y%m')
 ORDER BY YEAR ASC, MONTH ASC