SELECT H.FLAVOR
  FROM FIRST_HALF H
  JOIN (SELECT SUM(TOTAL_ORDER) AS SUM, FLAVOR
          FROM JULY
         GROUP BY FLAVOR) J
    ON H.FLAVOR=J.FLAVOR
 ORDER BY H.TOTAL_ORDER+J.SUM DESC
 LIMIT 3
