SELECT I.FLAVOR
  FROM (SELECT F.FLAVOR, F.TOTAL_ORDER+SUM(J.TOTAL_ORDER) AS TOTAL
  FROM FIRST_HALF AS F
  JOIN JULY AS J
    ON F.FLAVOR=J.FLAVOR
 GROUP BY F.FLAVOR
 ORDER BY TOTAL DESC
 LIMIT 3) AS I