SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
  FROM MEMBER_PROFILE P
  JOIN REST_REVIEW R
    ON P.MEMBER_ID=R.MEMBER_ID
  JOIN (SELECT MEMBER_ID
  FROM REST_REVIEW 
 GROUP BY MEMBER_ID
 ORDER BY COUNT(REVIEW_ID) DESC
 LIMIT 1) AS M
    ON P.MEMBER_ID=M.MEMBER_ID
 ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
  