-- 코드를 입력하세요
SELECT A.MCDP_CD AS '진료과 코드', A.CNT AS '5월예약건수'
  FROM (SELECT MCDP_CD, COUNT(*) AS CNT
  FROM APPOINTMENT
 WHERE DATE_FORMAT(APNT_YMD,'%Y%m')='202205'
 GROUP BY MCDP_CD) A
 ORDER BY A.CNT, A.MCDP_CD 
 ;
# SELECT *
#   FROM APPOINTMENT
#  where DATE_FORMAT(APNT_YMD,'%Y%m')='202205'