SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
  JOIN (SELECT CAR_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE DATE_FORMAT(START_DATE,'%Y%m') BETWEEN '202208' AND '202210'
 GROUP BY CAR_ID
 HAVING COUNT(CAR_ID)>=5) A
    ON H.CAR_ID=A.CAR_ID
 WHERE DATE_FORMAT(START_DATE,'%Y%m') BETWEEN '202208' AND '202210'
 GROUP BY MONTH(H.START_DATE), H.CAR_ID
 HAVING COUNT(*)>0
 ORDER BY MONTH(H.START_DATE) ASC, H.CAR_ID DESC