SELECT I.ID, N.FISH_NAME, I.LENGTH
  FROM FISH_INFO I
  JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE=N.FISH_TYPE
  JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
          FROM FISH_INFO F
         GROUP BY FISH_TYPE) F
    ON I.FISH_TYPE=F.FISH_TYPE
   AND I.LENGTH=F.LENGTH
 ORDER BY I.ID