-- 코드를 입력하세요
SELECT DISTINCT(CAR.CAR_ID) AS CAR_ID
  FROM CAR_RENTAL_COMPANY_CAR CAR, CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
 WHERE CAR.CAR_ID = HIS.CAR_ID
   AND CAR.CAR_TYPE = '세단'
   AND TO_CHAR(HIS.START_DATE,'YYYYMM') = '202210'
 ORDER BY CAR_ID DESC
    